### ISSUE TITLE
About the Readme

### ISSUE THREAD

**Issue by bkhnk48** [brunompacheco/brb#13]
Hello
Thank you a lot for your implementation. I have only one a question about your Readme
The file mentioned a paper of Yang et al 2007, I searched and found this one: "**Optimization Models for Training Belief-Rule-Based Systems**". Is it the paper that you implement?
If it is the case, I appreciate you a lot, because I deeply need the implementation of this paper.
Thank you for your time
PS: this is the paper that I suppose https://ieeexplore.ieee.org/abstract/document/4244562/

**Comment by bkhnk48** [comment]
Perhaps you mentioned: Belief Rule-Base Inference Methodology Using the Evidential Reasoning Approach—RIMER

**Comment by brunompacheco** [comment]
Hi!

Sorry for the late reply. Unfortunately, this was done so long ago that I do not recall which references were used. I should've mentioned it in the readme, my bad.

I have briefly looked at the paper and it seems to be right. Nevertheless, you can check if the equations match the ones implemented in the code.
