### ISSUE TITLE
interval

### ISSUE THREAD

**Issue by AlexavierSeville** [brunompacheco/brb#14]
When executing 'from interval import interval, inf', an error occurred: 'Cannot find reference 'interval' in 'interval.py'.Did I install wrong interval？

**Comment by brunompacheco** [comment]
I just realized neither `requirements.txt` nor `environment.yml` have interval. Which one have you installed?

**Comment by AlexavierSeville** [comment]
I installed interval at first，then I changed to pyinterval after the problem occurred. Now the problem is solved, thank you for your reply.
