### ISSUE TITLE
interval error

### ISSUE THREAD

**Issue by chouchouxia** [brunompacheco/brb#6]
hello, can you do me a favor? 
 I try to run "test.py" int brb project but found that interval is not found.
I input "pip install interval" in terminal and then found that:
  I can only do this: "from interval import Interval, Inf"
  and "from interval import interval, inf", "interval[1,2]" would cause error.

**Comment by brunompacheco** [comment]
Hey, we're actually using [PyInterval](https://pyinterval.readthedocs.io/en/latest/). You can install this library with `pip install pyinterval`. Let me know if this solves your problem :)

**Comment by chouchouxia** [comment]
it is helpful. Thanks♪(･ω･)ﾉ
