### ISSUE TITLE
UserWarning

### ISSUE THREAD

**Issue by Bothgone** [brunompacheco/brb#8]
hello, can you do me a favor?
I try to run "test.py" int brb project but there are some warnings:" The referential value ({1, 2}) will be converted to a continuous interval to make the comparison with the input (interval([1.0, 2.0])). This is not advised as may result in unexpected behavior. Please use an integer interval instead or convert the rule's referential value to continuous"Is this because of a problem with the pyinterval library?
And if i want to use my own rules, what should I do？

**Comment by Bothgone** [comment]
hello, I have solved the pyinterval library, and I want to know how to use my own rules? Please tell me, thanks

**Comment by brunompacheco** [comment]
Have a look at the Rule (at brb/rule.py) and the RuleBaseModel (at brb/brb.py) objects. I haven't written any manual, but the code has some useful comments and docstring.
